# Generated by Django 4.0.4 on 2022-06-16 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('branch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branchoffice')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branchoffice')),
            ],
        ),
        migrations.CreateModel(
            name='EventJoinMaintenance',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('maintenance_id', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('state', models.IntegerField()),
                ('branch', models.IntegerField()),
                ('type', models.IntegerField()),
                ('repetitions', models.PositiveSmallIntegerField()),
                ('frecuency', models.PositiveSmallIntegerField()),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventJoinOrder',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('state', models.IntegerField()),
                ('branch', models.IntegerField()),
                ('type', models.IntegerField()),
                ('client_name', models.CharField(max_length=60)),
                ('invoice_num', models.CharField(max_length=30)),
                ('espec_file_url', models.CharField(max_length=300)),
                ('num_pieces', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventJoinReparation',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reparation_id', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('state', models.IntegerField()),
                ('branch', models.IntegerField()),
                ('type', models.IntegerField()),
                ('reason', models.CharField(max_length=150)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('serial_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('purchase_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branchoffice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MachineState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePeriod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StepState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowJoinWSteps',
            fields=[
                ('workflow_id', models.IntegerField(primary_key=True, serialize=False)),
                ('workflow_label', models.CharField(max_length=20)),
                ('workflowstep_id', models.IntegerField()),
                ('step_order', models.SmallIntegerField()),
                ('machine', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowSteps',
            fields=[
                ('workflowsteps_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_order', models.SmallIntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='ReparationDetails',
            fields=[
                ('reparation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=150)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.priority')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=60)),
                ('invoice_num', models.CharField(max_length=30)),
                ('espec_file_url', models.CharField(max_length=300)),
                ('num_pieces', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceDetails',
            fields=[
                ('maintenance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repetitions', models.PositiveSmallIntegerField()),
                ('frecuency', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maintenanceperiod')),
            ],
        ),
        migrations.CreateModel(
            name='MachineWorkflowStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_order', models.SmallIntegerField()),
                ('end_datetime', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orderdetails')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stepstate')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machinestate'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventstate'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventtype'),
        ),
    ]
