# Generated by Django 4.0.4 on 2022-05-05 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id_branch', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branchoffice')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('serial_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('purchase_date', models.DateField()),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branchoffice')),
            ],
        ),
        migrations.CreateModel(
            name='MachineState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePeriod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('id_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_num', models.CharField(max_length=30)),
                ('espec_file_url', models.CharField(max_length=300)),
                ('cuts', models.PositiveSmallIntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tasktype')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taskstate'),
        ),
        migrations.CreateModel(
            name='ReparationDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=150)),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.priority')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repetitions', models.PositiveSmallIntegerField()),
                ('frecuency', models.PositiveSmallIntegerField()),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maintenanceperiod')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machinestate'),
        ),
    ]
