# Generated by Django 4.0.4 on 2022-06-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventjoineventstate',
            old_name='state_label',
            new_name='label',
        ),
    ]
