# Generated by Django 3.2.13 on 2022-08-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordersresumemodel_productivityreportmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventjoinorders',
            name='serial_numer',
            field=models.CharField(default='0000', max_length=20),
            preserve_default=False,
        ),
    ]
