# Generated by Django 4.0.4 on 2022-06-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_state_label_eventjoineventstate_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowjoinwsteps',
            old_name='workflow_label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='workflowjoinwsteps',
            old_name='workflowstep_id',
            new_name='workflowsteps_id',
        ),
    ]
