# Generated by Django 3.2.13 on 2022-08-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventjoinorders_serial_numer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineOrdersModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=20)),
                ('invoice_num', models.CharField(max_length=30)),
                ('client_name', models.CharField(max_length=60)),
                ('step_state', models.IntegerField()),
                ('schedule_date', models.DateTimeField()),
            ],
        ),
    ]
