# Generated by Django 4.0.4 on 2022-06-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_workflow_label_workflowjoinwsteps_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowjoinwsteps',
            old_name='step_activity',
            new_name='machine_type_label',
        ),
    ]
