# Generated by Django 4.0.4 on 2022-06-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_step_activity_workflowjoinwsteps_machine_type_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowjoinwsteps',
            old_name='machine_type_label',
            new_name='machinetype_label',
        ),
    ]
