# Generated by Django 4.0.4 on 2022-06-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_machine_type_label_workflowjoinwsteps_machinetype_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowjoinwsteps',
            old_name='workflowsteps_id',
            new_name='id_workflowsteps',
        ),
    ]
