# Generated by Django 4.0.4 on 2022-06-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_workflowsteps_id_workflowjoinwsteps_id_workflowsteps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowjoinwsteps',
            old_name='id_workflowsteps',
            new_name='step_id',
        ),
    ]
