# Generated by Django 4.0.4 on 2022-06-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_id_workflowsteps_workflowjoinwsteps_step_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowjoinwsteps',
            old_name='machinetype_label',
            new_name='type_label',
        ),
    ]
