# Generated by Django 4.0.4 on 2022-06-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_machinetype_label_workflowjoinwsteps_type_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventjoinorders',
            old_name='end_date',
            new_name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='eventjoinorders',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventjoinorders',
            name='num_pieces',
        ),
    ]
